#!/bin/bash

function runthem {
for i in {1..48}
do
echo $i | $prg > run-$i.log 2>&1 &
done
}


dir=`pwd`

prg="../pwhg_main"

cat powheg.input-save | sed 's/ncall2 *[0-9]* /ncall2 0 / '>powheg.input
echo 1 | $prg > run-0.log 2>&1

# wait until finished
wait
echo done > done0

cat powheg.input-save | sed 's/nubound *[0-9]* /nubound 0 /'>powheg.input
runthem
wait
echo done > done1

cat powheg.input-save | sed 's/numevts *[0-9]* /numevts 0 /'>powheg.input
runthem
wait
echo done > done2

cat powheg.input-save > powheg.input
runthem


